//
//  APIKeys.swift
//  SiloApp
//
//  Created by Cary Beam on 7/18/22.
//

import Foundation

enum ApiKey {
    
    static let deviceToken          = "devicetoken"
    static let deviceID             = "deviceId"
    static let platform             = "platform"
    static let timeZone             = "timezone"
    static let token                = "token"
    static let accessToken          = "accessToken"
    static let name                 = "name"
    static let userName             = "userName"
    static let email                = "email"
    static let password             = "password"
    static let countryCode          = "countryCode"
    static let phoneNo              = "phoneNo"
    static let fullPhoneNo          = "fullPhoneNo"
    static let otp                  = "otp"
    static let _id                  = "_id"
    static let userId               = "userId"
    static let authorization        = "authorization"
    static let assetId              = "asset_id"
    static let currencies           = "currencies"
    static let recoveryPhase        = "recovery_phase"
    static let cryptocurrencies     = "cryptocurrencies"
    static let walletAddress        = "wallet_address"
    static let currencyName         = "currency_name"
    static let pinSize              = "pin_size"
    static let resend               = "resend"
    static let isUpdate             = "isUpdate"
    static let forgotPasswordType   = "forgot_password_type"
    static let statusCode           = "statusCode"
    static let profilePhoto         = "profilePhoto"
    static let isFriend             = "isFriend"
    static let message              = "message"
    static let contactId            = "contactId"
    static let friendUserId         = "frienduserId"
    static let search               = "search"
    static let pageNo               = "pageNo"
    static let limit                = "limit"
    static let walletName           = "wallet_name"
    static let contactName          = "contactName"
    static let contacts             = "contacts"
    static let receiverId           = "receiverId"
    static let fiatCurrency         = "fiatCurrency"
    static let fiatAmount           = "fiatAmount"
    static let coinAmount           = "coinAmount"
    static let totalCoinAmount      = "totalCoinAmount"
    static let requestId            = "requestId"
    static let accountId            = "accountId"
    static let documentType         = "documentType"
    static let type                 = "type"
    static let routingNumber        = "routingNumber"
    static let accountNumber        = "accountNumber"
    static let firstNameOnAccount   = "firstNameOnAccount"
    static let lastNameOnAccount    = "lastNameOnAccount"
    static let accountType          = "accountType"
    static let beneficiaryType      = "beneficiaryType"
    static let country              = "country"
    static let currency             = "currency"
    static let notificationEnabled  = "notificationEnabled"
    static let dest                 = "dest"
    static let sourceCurrency       = "sourceCurrency"
    static let destCurrency         = "destCurrency"
    static let sourceAmount         = "sourceAmount"
    static let source               = "source"
    static let transferId           = "transferId"
    static let paymentMethodId      = "paymentMethodId"
    static let file                 = "file"
    static let birthDate            = "birth_date"
    static let state                = "state"
    static let city                 = "city"
    static let postalCode           = "postalCode"
    static let street1              = "street1"
    static let street2              = "street2"
    static let address              = "address"
    static let givenName            = "givenName"
    static let familyName           = "familyName"
    static let phone                = "phone"
    static let number               = "number"
    static let year                 = "year"
    static let month                = "month"
    static let cvv                  = "cvv"
    static let debitCard            = "debitCard"
    static let amount               = "amount"
    static let destAmount           = "destAmount"
    static let reservationId        = "reservationId"
    static let ipAddress            = "ipAddress"
    static let walletOrderId        = "walletOrderId"
    static let sms                  = "sms"
    static let card2fa              = "card2fa"
}
