//
//  AppImages.swift
//  SiloApp
//
//  Created by Cary Beam on 7/18/22.
//

import Foundation
import UIKit

enum AppImages {
    
    static let checkedBox               =   UIImage(named: "checkedBox")
    static let copy                     =   UIImage(named: "copy")
    static let cross                    =   UIImage(named: "cross")
    static let downArrow                =   UIImage(named: "downArrow")
    static let error                    =   UIImage(named: "error")
    static let hidePassword             =   UIImage(named: "hidePassword")
    static let logoWithName             =   UIImage(named: "logo_with_name")
    static let logo                     =   UIImage(named: "logo")
    static let profileUnselected        =   UIImage(named: "profileUnselected")
    static let receive                  =   UIImage(named: "receive")
    static let request                  =   UIImage(named: "request")
    static let scan                     =   UIImage(named: "scan")
    static let send                     =   UIImage(named: "send")
    static let showPassword             =   UIImage(named: "showPassword")
    static let correct                  =   UIImage(named: "correct")
    static let transactionUnselected    =   UIImage(named: "transactionUnselected")
    static let uncheckedBox             =   UIImage(named: "uncheckedBox")
    static let walletSelected           =   UIImage(named: "walletSelected")
    static let illustration1            =   UIImage(named: "illustration1")
    static let illustration2            =   UIImage(named: "illustration2")
    static let illustration3            =   UIImage(named: "illustration3")
    static let logout                   =   UIImage(named: "logout")
    static let tick                     =   UIImage(named: "tick")
    static let delete                   =   UIImage(named: "delete")
    static let assets                   =   UIImage(named: "assets")
    static let contactUs                =   UIImage(named: "contactUs")
    static let friends                  =   UIImage(named: "friends")
    static let requests                 =   UIImage(named: "requests")
    static let notifications            =   UIImage(named: "notifications")
    static let paymentMethods           =   UIImage(named: "paymentMethods")
    static let profilelogout            =   UIImage(named: "profilelogout")
    static let searchUsers              =   UIImage(named: "searchUsers")
    static let security                 =   UIImage(named: "security")
    static let settings                 =   UIImage(named: "settings")
    static let transactionsHistory      =   UIImage(named: "transactionsHistory")
    static let profilePlaceholder       =   UIImage(named: "profilePlaceholder")
    static let buy                      =   UIImage(named: "buy")
    static let sell                     =   UIImage(named: "sell")
    static let exchange                 =   UIImage(named: "exchange")
    static let dummyQR                  =   UIImage(named: "dummyQR")
    static let rightArrow               =   UIImage(named: "rightArrow")
    static let restore                  =   UIImage(named: "restore")
    static let faceId                   =   UIImage(named: "faceId")
    static let key                      =   UIImage(named: "key")
    static let lock                     =   UIImage(named: "lock")
    static let pin                      =   UIImage(named: "pin")
    static let viewBackupPhrase         =   UIImage(named: "viewBackupPhrase")
    static let success                  =   UIImage(named: "success")
    static let addFriend                =   UIImage(named: "addFriend")
    static let alreadyFriends           =   UIImage(named: "alreadyFriends")
    static let filter                   =   UIImage(named: "filter")
    static let add                      =   UIImage(named: "add")
    static let confirm                  =   UIImage(named: "confirm")
    static let failed                   =   UIImage(named: "failed")
    static let addWithBackground        =   UIImage(named: "addWithBackground")
    static let flash                    =   UIImage(named: "flash")
    static let gallery                  =   UIImage(named: "gallery")
    static let upArrow                  =   UIImage(named: "upArrow")
    static let paste                    =   UIImage(named: "paste")
    static let bank                     =   UIImage(named: "bank")
    static let interChange              =   UIImage(named: "interChange")
    static let creditDebitCard          =   UIImage(named: "creditDebitCard")
    static let calendar                 =   UIImage(named: "calendar")
    static let addDocument              =   UIImage(named: "addDocument")
    static let optionCamera             =   UIImage(named: "optionCamera")
    static let optionDocuments          =   UIImage(named: "optionDocuments")
    static let optionGallery            =   UIImage(named: "optionGallery")
    static let pdf                      =   UIImage(named: "pdf")
    static let requestWithBackground    =   UIImage(named: "requestWithBackground")
    static let sendWithBackground       =   UIImage(named: "sendWithBackground")
    static let kycCompleted             =   UIImage(named: "kycCompleted")
    static let kycInProgress            =   UIImage(named: "kycInProgress")
    static let kycPending               =   UIImage(named: "kycPending")
    static let back                     =   UIImage(named: "back")
}
